# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2521bcffc10c8d131cf16741dc09edd1cd246296935caa3f650e1ac3c833d1d0204e685f6d8bc9916792c132d239080606ad7806f3dd9ad142a22ad13445bac

test:
  secret_key_base: b690f0bf7ccfff4c7f9d1097307f916c55fe0fb680da1f95e9738338cf36cab97a329686ff80c05aee89cf3e1f3fee31752c1ab525c213bbec6743de47c43000

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
